sensor_frame: 'camera_rgb_optical_frame'
use_rgb: true
max_queue_size: 1
keep_organized: true
self_see_links:
  -
    name: 'jaco_base_link_simplified'
    padding: 0.02
  -
    name: 'jaco_upper_arm_link_simplified'
    padding: 0.02
  -
    name: 'jaco_forearm_link_simplified'
    padding: 0.02
  -
    name: 'jaco_wrist_1_link_simplified'
    padding: 0.02
  -
    name: 'jaco_wrist_2_link_simplified'
    padding: 0.02
  -
    name: 'jaco_wrist_3_link_simplified'
    padding: 0.02
  -
    name: 'arm_mount_beam_link'
    padding: 0.02
  -
    name: 'arm_mount_plate_link'
    padding: 0.02